import { useState } from "react";
import { ArrowLeft, Mail } from "lucide-react";

interface ForgotPasswordProps { onBack: () => void; onContinue: (email: string) => Promise<void> }
export function ForgotPassword({ onBack, onContinue }: ForgotPasswordProps) {
  const [email,setEmail]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [sent,setSent]=useState(false);
  const submit=async()=>{if(!email.includes("@"))return setError("Enter a valid email address.");setLoading(true);setError("");try{await onContinue(email.trim());setSent(true);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to send reset email.");}finally{setLoading(false);}};
  return <div className="size-full bg-[#fcfcfd] flex flex-col"><div className="h-[max(env(safe-area-inset-top),8px)]"/><header className="px-6 py-5"><button onClick={onBack}><ArrowLeft className="size-5"/></button></header><main className="flex-1 px-6 max-w-md w-full mx-auto"><div className="size-14 rounded-full bg-[#fef0f3] grid place-items-center mb-6"><Mail className="text-[#fe456a]"/></div><h1 className="text-2xl font-semibold text-[#1f2a37]">Reset your password</h1>{sent?<div className="mt-5 rounded-xl bg-green-50 border border-green-200 p-4 text-sm text-green-800">Check your email and open the password-reset link. You can close this page.</div>:<><p className="mt-2 text-sm text-[#6b7280]">Enter the email address connected to your Roomie account.</p><label className="block text-sm font-medium mt-8 mb-2">Email address</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="you@example.com" className="w-full h-12 rounded-xl border px-4 outline-none focus:border-[#fe456a]"/>{error&&<p className="text-sm text-red-500 mt-2">{error}</p>}<button onClick={submit} disabled={loading} className="mt-6 w-full h-12 rounded-lg bg-[#fe456a] text-white font-semibold disabled:opacity-60">{loading?"Sending…":"Send reset link"}</button></>}</main></div>;
}
