import { useEffect, useState } from "react";
import { ArrowLeft, MapPin, Navigation, Search } from "lucide-react";

export interface SelectedMapLocation { address: string; city: string; country: string; latitude: number; longitude: number }
interface MapsScreenProps { onBack: () => void; onChooseLocation: (location: SelectedMapLocation) => void; autoLocate?: boolean }

const normalize = (result: any): SelectedMapLocation => ({ address: result.display_name ?? "Selected location", city: result.address?.city || result.address?.town || result.address?.village || result.address?.county || "", country: result.address?.country || "", latitude: Number(result.lat), longitude: Number(result.lon) });

export function MapsScreen({ onBack, onChooseLocation, autoLocate = false }: MapsScreenProps) {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<any[]>([]); const [selected, setSelected] = useState<SelectedMapLocation | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const reverse = async (latitude: number, longitude: number) => { const response = await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${latitude}&lon=${longitude}&addressdetails=1`); if (!response.ok) throw new Error("Location lookup failed"); const location=normalize(await response.json()); setSelected(location); };
  const locate = () => { setLoading(true); setError(""); if (!navigator.geolocation) { setLoading(false); return setError("Location is not supported on this device."); } navigator.geolocation.getCurrentPosition(async ({coords}) => { try { await reverse(coords.latitude,coords.longitude); } catch(e){setError(e instanceof Error?e.message:"Unable to find address");} finally{setLoading(false);} }, (reason)=>{setLoading(false);setError(reason.message || "Location permission was denied.");}, {enableHighAccuracy:true,timeout:15000}); };
  useEffect(()=>{if(autoLocate)locate();},[autoLocate]);
  useEffect(()=>{ if(query.trim().length<3){setResults([]);return;} const timer=setTimeout(async()=>{setLoading(true);try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=6&q=${encodeURIComponent(query)}`);setResults(response.ok?await response.json():[]);}finally{setLoading(false);}},500);return()=>clearTimeout(timer);},[query]);
  const mapUrl=selected?`https://www.openstreetmap.org/export/embed.html?bbox=${selected.longitude-0.02}%2C${selected.latitude-0.015}%2C${selected.longitude+0.02}%2C${selected.latitude+0.015}&layer=mapnik&marker=${selected.latitude}%2C${selected.longitude}`:"https://www.openstreetmap.org/export/embed.html?bbox=28.8%2C-2.1%2C30.4%2C-1.2&layer=mapnik";
  return <div className="size-full flex flex-col bg-[#f8fafc]"><div className="h-[max(env(safe-area-inset-top),8px)] bg-white"/><header className="bg-white px-5 py-4 border-b flex items-center gap-4"><button onClick={onBack}><ArrowLeft/></button><h1 className="font-semibold text-lg">Choose your location</h1></header><div className="relative flex-1 min-h-0"><iframe title="OpenStreetMap location" src={mapUrl} className="absolute inset-0 size-full border-0"/><div className="absolute top-4 left-4 right-4 z-10"><div className="bg-white shadow-lg rounded-xl px-4 h-12 flex items-center gap-2"><Search className="size-5 text-[#fe456a]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search city, area, or address" className="flex-1 outline-none text-sm"/><button onClick={locate} aria-label="Use current location"><Navigation className="size-5 text-[#fe456a]"/></button></div>{results.length>0&&<div className="mt-2 bg-white shadow-xl rounded-xl overflow-hidden max-h-64 overflow-y-auto">{results.map(result=><button key={result.place_id} onClick={()=>{setSelected(normalize(result));setResults([]);setQuery("");}} className="w-full text-left px-4 py-3 border-b last:border-0 flex gap-2"><MapPin className="size-4 mt-1 text-[#fe456a] shrink-0"/><span className="text-sm">{result.display_name}</span></button>)}</div>}</div></div><div className="bg-white border-t p-5"><p className="text-sm font-medium text-[#1f2a37]">{selected?.address || (loading?"Finding location…":"Search or use your current location")}</p>{error&&<p className="text-sm text-red-500 mt-2">{error}</p>}<button disabled={!selected||loading} onClick={()=>selected&&onChooseLocation(selected)} className="mt-4 w-full h-12 rounded-lg bg-[#fe456a] text-white font-semibold disabled:bg-gray-300">Choose location</button><p className="text-[11px] text-gray-400 text-center mt-2">Map data © OpenStreetMap contributors</p></div></div>;
}
