import { useEffect, useState } from "react";
import { ArrowLeft, Heart, Clock, MapPin } from "lucide-react";
import { supabase } from "../../lib/supabase";
import { useAuth } from "../auth/AuthProvider";

export function SavedListings({ mode, onBack }: { mode:"favorites"|"recent"; onBack:()=>void }) {
  const { user } = useAuth(); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{ if(!user)return; const table=mode==="favorites"?"listing_favorites":"listing_views"; const order=mode==="favorites"?"created_at":"viewed_at"; supabase.from(table).select("listings(id,title,rent,area,city,listing_photos(storage_path))").eq("user_id",user.id).order(order,{ascending:false}).then(({data})=>{setRows((data??[]).map((r:any)=>r.listings).filter(Boolean));setLoading(false);});},[mode,user]);
  return <div className="min-h-screen bg-[#fafafa]"><div className="h-[max(env(safe-area-inset-top),8px)]"/><header className="bg-white border-b px-5 py-4 flex items-center gap-4"><button onClick={onBack}><ArrowLeft/></button><h1 className="font-semibold text-lg">{mode==="favorites"?"Favorites":"Recently Viewed"}</h1></header><main className="p-5">{loading?<p className="text-center text-[#9da4ae] py-12">Loading…</p>:rows.length?<div className="grid gap-4 sm:grid-cols-2">{rows.map((listing:any)=>{const path=listing.listing_photos?.[0]?.storage_path;const image=path?supabase.storage.from("listing-photos").getPublicUrl(path).data.publicUrl:null;return <article key={listing.id} className="bg-white border rounded-xl overflow-hidden">{image?<img src={image} className="w-full h-40 object-cover" alt=""/>:<div className="h-32 bg-gray-100"/>}<div className="p-4"><h2 className="font-semibold">{listing.title}</h2><p className="text-sm text-gray-500 flex gap-1 mt-2"><MapPin size={14}/>{listing.area}, {listing.city}</p><p className="font-bold text-[#fe456a] mt-2">{listing.rent}/month</p></div></article>})}</div>:<div className="text-center py-20 text-[#9da4ae]">{mode==="favorites"?<Heart className="mx-auto mb-3"/>:<Clock className="mx-auto mb-3"/>}<p>No {mode==="favorites"?"favorite listings":"recently viewed listings"} yet.</p></div>}</main></div>;
}
