create extension if not exists pgcrypto;
create type public.user_role as enum ('user','admin');
create type public.listing_status as enum ('draft','published','archived');
create type public.request_status as enum ('pending','accepted','declined');

create table public.profiles (id uuid primary key references auth.users on delete cascade, username text not null unique, full_name text, avatar_url text, bio text, city text, role public.user_role not null default 'user', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.preferences (user_id uuid primary key references public.profiles on delete cascade, answers jsonb not null default '{}', updated_at timestamptz not null default now());
create table public.listings (id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles on delete cascade, intent text not null check(intent in ('roommate','rental')), living_setup text not null, title text not null, description text not null default '', country text not null, city text not null, area text not null, address text, hide_address boolean not null default false, rent numeric(12,2) not null check(rent>=0), deposit numeric(12,2) not null default 0, move_in_date date not null, minimum_stay text not null, details jsonb not null default '{}', ideal_for text[] not null default '{}', status public.listing_status not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index listings_discovery_idx on public.listings(status,city,rent);
create table public.listing_photos (id uuid primary key default gen_random_uuid(), listing_id uuid not null references public.listings on delete cascade, storage_path text not null, position int not null default 0, created_at timestamptz not null default now(), unique(listing_id,position));
create table public.booking_requests (id uuid primary key default gen_random_uuid(), listing_id uuid not null references public.listings on delete cascade, requester_id uuid not null references public.profiles on delete cascade, owner_id uuid not null references public.profiles on delete cascade, message text, status public.request_status not null default 'pending', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(listing_id,requester_id), check(requester_id<>owner_id));
create table public.conversations (id uuid primary key default gen_random_uuid(), request_id uuid unique references public.booking_requests on delete set null, created_at timestamptz not null default now());
create table public.conversation_members (conversation_id uuid references public.conversations on delete cascade, user_id uuid references public.profiles on delete cascade, last_read_at timestamptz, primary key(conversation_id,user_id));
create table public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations on delete cascade, sender_id uuid not null references public.profiles on delete cascade, body text not null check(char_length(body) between 1 and 4000), created_at timestamptz not null default now());
create index messages_conversation_idx on public.messages(conversation_id,created_at);
create table public.posts (id uuid primary key default gen_random_uuid(), author_id uuid not null references public.profiles on delete cascade, body text not null, image_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.post_likes (post_id uuid references public.posts on delete cascade, user_id uuid references public.profiles on delete cascade, created_at timestamptz not null default now(), primary key(post_id,user_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, actor_id uuid references public.profiles on delete set null, type text not null, entity_id uuid, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());

create function public.create_profile_for_user() returns trigger security definer set search_path=public language plpgsql as $$ begin insert into public.profiles(id,username,full_name,avatar_url) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'username',''),split_part(new.email,'@',1)||'_'||substr(new.id::text,1,6)),new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'avatar_url'); return new; end $$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.create_profile_for_user();

alter table public.profiles enable row level security; alter table public.preferences enable row level security; alter table public.listings enable row level security; alter table public.listing_photos enable row level security; alter table public.booking_requests enable row level security; alter table public.conversations enable row level security; alter table public.conversation_members enable row level security; alter table public.messages enable row level security; alter table public.posts enable row level security; alter table public.post_likes enable row level security; alter table public.notifications enable row level security;
create policy "profiles read" on public.profiles for select to authenticated using(true); create policy "profile owner update" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "own preferences" on public.preferences for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "listings read" on public.listings for select using(status='published' or owner_id=auth.uid()); create policy "listing owner write" on public.listings for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "photos read" on public.listing_photos for select using(true); create policy "photos owner write" on public.listing_photos for all to authenticated using(exists(select 1 from public.listings l where l.id=listing_id and l.owner_id=auth.uid())) with check(exists(select 1 from public.listings l where l.id=listing_id and l.owner_id=auth.uid()));
create policy "requests participant read" on public.booking_requests for select to authenticated using(auth.uid() in (requester_id,owner_id)); create policy "request create" on public.booking_requests for insert to authenticated with check(requester_id=auth.uid()); create policy "request owner update" on public.booking_requests for update to authenticated using(owner_id=auth.uid());
create policy "conversation member read" on public.conversations for select to authenticated using(exists(select 1 from public.conversation_members m where m.conversation_id=id and m.user_id=auth.uid())); create policy "members read" on public.conversation_members for select to authenticated using(user_id=auth.uid());
create policy "messages read" on public.messages for select to authenticated using(exists(select 1 from public.conversation_members m where m.conversation_id=conversation_id and m.user_id=auth.uid())); create policy "messages send" on public.messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.conversation_members m where m.conversation_id=conversation_id and m.user_id=auth.uid()));
create policy "posts read" on public.posts for select using(true); create policy "posts own" on public.posts for all to authenticated using(author_id=auth.uid()) with check(author_id=auth.uid()); create policy "likes read" on public.post_likes for select using(true); create policy "likes own" on public.post_likes for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "notifications own" on public.notifications for select to authenticated using(user_id=auth.uid()); create policy "notifications update" on public.notifications for update to authenticated using(user_id=auth.uid());

insert into storage.buckets(id,name,public) values('avatars','avatars',true),('listing-photos','listing-photos',true),('post-images','post-images',true) on conflict do nothing;
create policy "media read" on storage.objects for select using(bucket_id in ('avatars','listing-photos','post-images')); create policy "media upload" on storage.objects for insert to authenticated with check((storage.foldername(name))[1]=auth.uid()::text); create policy "media update" on storage.objects for update to authenticated using((storage.foldername(name))[1]=auth.uid()::text); create policy "media delete" on storage.objects for delete to authenticated using((storage.foldername(name))[1]=auth.uid()::text);
alter publication supabase_realtime add table public.messages,public.notifications,public.booking_requests;
